### ISSUE TITLE
Compability with AspectAbilities mod

### ISSUE THREAD

**Issue by benjdidj** [William758/ZetAspects#1]
Any way that there is a compability with https://thunderstore.io/package/TheMysticSword/AspectAbilities/, 

i like that mod for the activable aspect but i think i am going to love yours for the stacks and other effects.

**Comment by William758** [comment]
The mod can already detect if you have the equipment version of an aspect but equipment drops are overwritten by default.
At the top of the config, you can change eliteEquipment = false to eliteEquipment = true so that killing elite monsters still drops the equipment. you will still be able to find the red tier items from chests.

**Comment by benjdidj** [comment]
I tried your mod without aspect abilities,  
Even at 100 % elite dont drop their aspect. 
Are they supposed to drop it only if eliteEquipement=true, if not only  from chest. 
Just to be sure i understand right. Thx anyway.

**Comment by William758** [comment]
eliteEquipement only changes whether to drop the new red item or the original equipment.
do you have another mod that would be changing the drop rate?
the setting should say dropChance = 100 for 100%
Im currently using aspect abilities and everything seems to work fine.

**Comment by benjdidj** [comment]
i tried in a new profile all the mods i thought were problematic. everythings works fine. So sorry about that. have no idea whats causing my issue, i'll continue tracking it. thx

**Comment by William758** [comment]
Cool, let me know if you find out what the issue was so I can try and fix it.

**Comment by benjdidj** [comment]
I think that it is BetterTeleporter that prevented drops from monsters. 
I tested with your Aspectropchance=100 and 100% on all sivsItems'cfgs (Drops from basic monster), No drops. Without, everythings fine, for all drops.
your mod works fine.
I could not have guess there was a link. 
TYhis mod makes tp charge faster by killing enemies while in Tp range.
thx for the mod.

**Comment by benjdidj** [comment]
While i am at it, would there be a way that after u have an aspect equipement, only red aspect can drop for this aspect.

Ex: i have a fire aspect, other fire aspect dropping are red but lightning aspect still can drop as an equipement, or ice or.. until i swap.

**Comment by William758** [comment]
I originally didn't plan for letting the equipment drop but I saw Aspect Abilities and added support for detecting equipment.
Maybe I'll make it so picking up an aspect equipment while holding the same one converts it into the red item?
I also didn't get any drops when I installed BetterTeleporter.

**Comment by benjdidj** [comment]
Very cool if u could do that.
Yeah,BetterTp seems to prevent Tp drops too.
