### ISSUE TITLE
Tinkering Elite Monster Behavior

### ISSUE THREAD

**Issue by Scrublord1337** [William758/ZetAspects#13]
Hello,

First off just want to say I love this mod, me and my friends have been using it for months. It's really cool that you added support for the Elite Variety mod so quickly after it released. While I was playing around with the configuration I did notice something that Zetaspects seems to change about the tinkering elite monster behavior that seems unintentional to me.

When Tinkering Elites spawn in they will not begin spawning any drones until they take damage from the player or an ally on the player team. This seems to be consistent regardless of whether the aspects are set to be items or equipment. This only seems to affect monsters, if a player gains the tinkering aspect they will spawn drones as soon as they can. Without Zetaspects installed tinkering elite monsters will act this way, they will spawn drones as soon as they spawn into the stage.

I have attached a bepinex log. Right down at the bottom I was able to get a tinkering elite to spawn and attacked it to cause it to spawn its drone. It is surrounded by messages from TILER2 but that doesn't seems to affect much. Hope this helps.
[TinkeringElite_Zetaspects.txt](https://github.com/William758/ZetAspects/files/6689668/TinkeringElite_Zetaspects.txt)

Thanks

**Comment by William758** [comment]
Just posted an update to fix Tinkerer Drones not immediately spawning.
