### ISSUE TITLE
Equipment Aspects question

### ISSUE THREAD

**Issue by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [William758/ZetAspects#14]
Is it possible to implement fixed icons, names, descriptions and logbook entries for Aspects when set to Equipments (just like yellow or red versions), or are they hard-coded into the game?

**Comment by William758** [comment]
I haven't looked into how the log hides the aspect equipment but it should be doable. Updating the equipment texts and icons should be relatively simple. I'll include these changes at some point when I update the mod again.

**Comment by William758** [comment]
Trying to get the equipment to show in the logbook looked like it would be messy, so for now I made picking up the equipment discover the associated item in the logbook. I've also included aspect effects it the equipment description.

**Comment by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [comment]
Thank you very much, it was mostly a problem mid-run because you lacked all of the information pertaining to the aspects (and I recently discovered Aspect Abilities, so I couldn't back down), but now that's solved. Thanks again.
