### ISSUE TITLE
Third Wish + 57 Leaf Clover, and some other Third Wish feed back.

### ISSUE THREAD

**Issue by Khanti32167** [William758/ZetAspects#15]
When I picked up these two items, the clover sound effect starting going off like crazy. At 1st I wasn't sure what was causing it, but then remembered I had recently picked up the Aspect "The Third Wish" which creates the sand tornado around your character. When I used another mod I had installed to drop it, the sounds stopped. Then I picked it up again, the clover sound effect started going crazy again. I am assuming that the tornado is based on some kind of auto attacking function that has a proc coefficient attached to it. Since the tornado hits so rapidly, it was constantly landing attacks that would have caused something like my tri tip daggers, a critical hit, or stun grenade to proc, even though it wasnt coming into contact with any enemies. I also found that the tornado when combo-ed with certain other things, such as "Silence Between Two Strikes", and "Her Biting Embrace", became very broken with the tornado active. I was able to just stand next to Mithrix and "Her Biting Embrace" was causing him to become permafrozen, and then caused the glitch where you skip his final phase. So if there is a a proc coefficient which there does seem to be on the tornado, I would propose making it 0. Maybe increase its damage a little to make up for the lack of proc coefficient, although that could result in some early deaths because that thing butchers people in the early stages when an enemy spawns with it. So could you look into removing the proc coefficient, or adding a setting in the config to adjust it on our own. Thanks.

**Comment by William758** [comment]
I can't really change the behavior of The Third Wish as that's from the mod EliteVariety.
I've made an issue over at https://github.com/TheMysticSword/EliteVariety/issues/36

Also Her Biting Embrace shouldn't be freezing Mithrix anymore. I suspect you also had Permafrost from classic items.

**Comment by Khanti32167** [comment]
No, i dont use classic items in my mod set. It was definetly being triggered by embrace. Thinking about it now, embrace was building chilled stacks, a function and behavior associated to the Artificer Extended mod. So that may have been what was causing the freeze to occur.On Jul 10, 2021 7:02 AM, William758 ***@***.***> wrote:
I can't really change the behavior of The Third Wish as that's from the mod EliteVariety.
I've made an issue over at TheMysticSword/EliteVariety#36
Also Her Biting Embrace shouldn't be freezing Mithrix anymore. I suspect you also had Permafrost from classic items.

**Comment by William758** [comment]
I've pushed an update that prevents the aspects from stacking chill and instead refresh any active chill duration.

**Comment by gaforb** [comment]
Good fix, but if you can land attacks in quick enough succession (for example, commando's phase blast with primary) you can still build stacks of chill and eventually freeze enemies when AE is installed.

**Comment by William758** [comment]
So the aspects were still applying a 0 second chill and I think if you hit in the same frame it would get refreshed to 4 seconds. The new patch should prevent chill from stacking from the aspects.

**Comment by William758** [comment]
I've gone ahead and added a config that needs to be enabled to lower the proc rate and prevent the sandstorm from critting.
