### ISSUE TITLE
Translation.

### ISSUE THREAD

**Issue by ghost** [William758/ZetAspects#17]
Hello. I love your work and mainly 3 of your mods I would love to translate and support its translation in the future for my native language (Turkish). I tanslated Star Conflict from Gaijin and TLD mod for Mount and Blade warband in the past. I recently finished translating Starstorm 2 mod as well, so you can trust my work and quality. The mods I want to translate is mainly ZetAspects, ZetArtifacts and CorpseBloomReborn. The reason I am asking this from you is because I play this game with my brother and these mods are very importand for us, I love him so much I do whatever to make him happier and this is one of those opportunities.

 Thank you for you time and if you are intereseted Please reach out to me (from Discord if possible), My discord accout is: 
   Omar Faruk#7906

**Comment by William758** [comment]
Hey, sorry for getting back to you so late. I would gladly include your translations in my mods. I don't have an complete list of all the text in my mods available as they are created in the code itself. Would you like me to get all the text and put them on one file for easier translation? ZetArtifacts should be simple to translate but ZetAspects and CorpseBloomReborn are more complex and create their text based on config settings.

**Comment by OmarFaruk46** [comment]
Yes of course! I would love that! Send me the file whenever you feel like it. I am also active on Discord if its easier for you to send it from there. Thank you!

**Comment by William758** [comment]
I've sent you a friend request on discord as TPDespair as I couldn't find you on the regular modding discord.

Here is the combined text from my mods for translation.
[merged_lang_tr.txt](https://github.com/William758/ZetAspects/files/7193706/merged_lang_tr.txt)

**Comment by mchobbylong** [comment]
Any updates on this? I would also love to contribution translation for ZetAspects, but looks like there are no localization files for different languages, but hard-coded texts.

**Comment by William758** [comment]
[zetaspects_tokens.txt](https://github.com/William758/ZetAspects/files/8884886/zetaspects_tokens.txt)

Here is an up to date list of all the text used to build items descriptions in the mod.

**Comment by ggang-b** [comment]
I want a translation, but the zetaspects_tokens.txt file seems out of date. There is no content about BlitteredElite. Could you share it again?

**Comment by William758** [comment]
I've just updated the file to include the blighted tokens.

https://github.com/William758/ZetAspects/blob/main/zetaspects_tokens.txt

You can send me the file here or use my Discord: TPDespair#7703
