### ISSUE TITLE
Lost in Transit

### ISSUE THREAD

**Issue by ghost** [William758/ZetAspects#18]
Can you support Lost in Transit mod's elite varient as well please? It's about bringing back some of the RoR1 Elite variants.

**Comment by William758** [comment]
Yeah I've been thinking about it but I've been busy lately. Frenzy should be pretty strait forward, but I want to make the leeching elite apply leeched damage over time and I'll have to code that myself.

**Comment by OmarFaruk46** [comment]
Thank you!

**Comment by William758** [comment]
I've added in some basic support for the new elites. I felt that the effects for them we already powerful so currently they don't have any stacking effects.

**Comment by OmarFaruk46** [comment]
I agree, but it would be great if it was in line with other aspects. Maybe a nerfed version of their powers can be better with stacking on top?

**Comment by William758** [comment]
I've managed to modify them to bring them in line with the other aspects and added stacking behavior.

**Comment by OmarFaruk46** [comment]
Yup. That looks great! Thanks for everything

**Comment by OmarFaruk46** [comment]
It seems like primodial rage gives you skill cooldown instead of movement speed (it says movement and attack speed on its card) also its icon is blamk yellow square. I personally prefer cooldown over speed since we have not many of them in game.

**Comment by William758** [comment]
Just added configs and text for the cooldown effect. LostInTransit are aware of the icon issue and will have to fix their icon on their end.
