### ISSUE TITLE
[Feature Request] Tinkerer's Drones to drop stolen scrap

### ISSUE THREAD

**Issue by XuaTheGrate** [William758/ZetAspects#19]
The mod is great, however I think it's a bit unfair for enemy drones to steal scrap and not be able to return when killed. If this could be added whether by config or by default that would be greatly welcomed, thanks.

**Comment by William758** [comment]
I've made an issue over at the mod authors page.

Hopefully they change the behavior because otherwise I'll have to figure out how to mod a mod.

**Comment by William758** [comment]
I've added a config that needs to be enabled that prevents tinker drones from stealing scrap. Not exactly what you wanted but close enough.
