### ISSUE TITLE
Having an aspect equipement makes red aspect drop.

### ISSUE THREAD

**Issue by benjdidj** [William758/ZetAspects#2]
While i am at it, would there be a way that after u have an aspect equipement, only red aspect can drop for this aspect.

Ex: i have a fire aspect, other fire aspect dropping are red but lightning aspect still can drop as an equipement, or ice or.. until i swap.

**Comment by William758** [comment]
Alright, I just uploaded an update that allows you to get the red item when you try picking up the same equipment.

**Comment by benjdidj** [comment]
THX
