### ISSUE TITLE
Aspect Equipments descriptions optimization

### ISSUE THREAD

**Issue by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [William758/ZetAspects#20]
There are a few lines featured in Aspect Equipments descriptions that could potentially be cut for simplicity's sake.
Currently, if Aspects are set to be Equipments, they will display a "per stack" statistic in their description. I know they can potentially be stacked with their Boss (yellow) counterparts, but it's a bit confusing if someone only uses the equipment versions and not these systems. Could this be removed, just for the Equipment descriptions? For the same reason, if eliteEquipmentEffect is set to 1, could the "Counts as 1 stack" line also be removed, for being a bit redundant?

Finally, I wanted to make the Lighting Aspect stats in line with Moffein's EliteReworks mod, so I tried setting lightningBaseShieldGained and lightningAddedShieldGained both to 0, and noticed ingame that the item description will say "Convert 0% of health into regenerating shields." Would it be possible for the entire line of a stat change to be hidden if it's set to 0? Maybe a boolean option could be implemented to hide them?

**Comment by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [comment]
Would it also be possible to have a config to Enable/Disable yellow logbook entries if the aspects are set as equipments?

**Comment by William758** [comment]
The latest update fixes 0% conversion text and removes the "Counts as 1 stack" text.

I currently reuse the item description for the equipment description so ill have to redo how equipment descriptions are built.
