### ISSUE TITLE
Ice Elites blade procs infinitely with BORBO

### ISSUE THREAD

**Issue by ed-ict** [William758/ZetAspects#21]
Hi there,

Thanks for the excellent mod. Wanted to give you a heads up that when BORBO is used in tandem with this mod, Ice Elites do not fire off a single blade but rather a continuous stream of blades. My best guess is that this may be due to the way BORBO currently modifies the Razorwire item and changes its internal cooldown.

This issue persists when Her Biting Embrace is picked up as an Elite Aspect. Survivor attacks create infinite blades, and since the blades have a proc coefficient, landing a single hit can rapidly obliterate all monsters on the map with only a single Ukulele. The lightning bounce seems to count as a new source of damage, so it tags all the monsters hit for new streams of infinite blades, which just keep applying exponential amounts of on hit effects.

Honestly, if it weren't for how much stronger it makes survivors, the glitched behaviour is actually pretty cool. Getting tagged by an ice elite isn't that punishing in the base game, but being hit with a constant stream of ice shards that trap you in the explosion radius (once you kill the elite) is actually an interesting gameplay mechanic if you get too close.

**Comment by William758** [comment]
I'm guessing that since BORBO changes razorwires proccoefficient it allowed the ice aspect to proc itself.

I've gone ahead and added a flag to the effect that prevents it (and razorwire) from procing itself if BORBO is installed.
