### ISSUE TITLE
Equipment Aspects Logbook Entries

### ISSUE THREAD

**Issue by eGhpGZeMqhlAIRtA1soVFK4JCDnrsxAXjirz97L** [William758/ZetAspects#29]
Version 1.2.7 of Wolfo's SlightlyFasterInteractables mod features logbook entries for the vanilla aspect equipments. Would this feature be possible to implement in ZetAspects?

**Comment by William758** [comment]
Yeah Shared Design is a Lunar Equipment. I've made is so that the equipment won't show up in the Rulebook, as the only way to obtain them is from elite drops. The items should now only appear in the Rulebook if they are set to not be WorldUnique.
