### ISSUE TITLE
Spectral Circlet doesn't seem to give any additional armor.

### ISSUE THREAD

**Issue by Nordblum** [William758/ZetAspects#3]
On paper, it's supposed to give the player +60 (+30) armor. I'm using [BetterUI](https://thunderstore.io/package/XoXFaby/BetterUI/) mod to show player stats, and according to the stats displayed - picking up Spectral Circlet or killing a celestial elite with Wake of Vultures doesn't add any armor. Maybe it's BetterUI's problem, but other mods that have items with armor changing properties work fine and BetterUI shows the changes accordingly.

**Comment by William758** [comment]
I was not able to replicate the issue with the mods I use. Using BetterUI showed that I was gaining armor. I'm guessing that some other item mod broke my armor hook. If you post an error log, I should be able to track down the issue.

**Comment by William758** [comment]
Actually, it looks like TILER2 just breaks most of my mods player stats so ill get around to fixing that.

**Comment by Nordblum** [comment]
Thank you very much for fixing this.
