### ISSUE TITLE
Other mod aspects not being converted to items, use ITEM_ZETASPECT(element)_NAME for name

### ISSUE THREAD

**Issue by jlaine3333** [William758/ZetAspects#33]
Lost In Transit, Aetherium, and EliteVariety aspects remain as equipment no matter what I try, even by picking up a duplicate or clicking it in the corner like the config says. Still happens when turning off any applicable config options, turning aspects into red items, etc. In addition, all aspects from the mod show as their default name, like ITEM_ZETASPECTFIRE_NAME.

**Comment by William758** [comment]
I'm pretty sure another mod is breaking the logbook which I use to setup text and mod compatibility, so I just uploaded a fix.

**Comment by Athermancer** [comment]
Is there a way to use the version you have up on github currently to see if it fixes this issue?
