### ISSUE TITLE
Suggestion: implement Tier 1 and Tier 2 specific drop rates

### ISSUE THREAD

**Issue by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [William758/ZetAspects#35]
A useful feature to ensure that Tier 2 aspects are at least almost as common as Tier 1 aspects would be to implement configs for setting drop rates for Tier 1/Tier 2 aspects specifically, or individual aspects even (although it might take longer to do this especially when paired with mods adding elite types).

Because Tier 2 elites take long to actually encounter, and even if using the Artifact of Escalation (which unfortunately doesn't currently work because of the EliteAPI) they are far less common, this option would help mitigate that and let players make Tier 2 aspects just as common to obtain if they so desire.

**Comment by William758** [comment]
I've gone ahead and added a config to generate additional configs to configure a drop chance multiplier for each elite type.
