### ISSUE TITLE
Suggestion: Make Entropic Fracture a Void item if aspectRedTier is enabled

### ISSUE THREAD

**Issue by u-lulu** [William758/ZetAspects#36]
Entropic Fracture, being a Void aspect, would be much more fitting as a proper Void+Red Item that corrupts all Aspects, for a few reasons:
- There is an obvious thematic connection.
- Enemies that become Voidtouched via infestor have their own elite aspect overwritten; this would be an equivalent effect happening to the player.
- It would be an interesting gameplay decision, because Entropic Fracture is unequivocally the _best_ aspect for damage, but choosing to take it forfeits the possibility of obtaining the other, more utility-focused effects that the other aspects provide.

The only issue I see with this implementation would be that it causes Entropic Fracture to become exceedingly rare compared to the rest of the Aspects, due to how inherently uncommon Void+Red items are in vanilla.

**Comment by William758** [comment]
Yeah I can add a config to make the void aspect a void tier item. I haven't checked how void transformations are set up yet so I'll have to look into that.

**Comment by William758** [comment]
I've gone ahead and added a config (disabled by default) in the void aspect section to change it into a void item. It only works on other itemized aspects currently so equipment and other sources of aspect buffs are not affected. I'll probably add another config that converts equipment and prevents gaining the other elite buffs.
