### ISSUE TITLE
Artifact of Command QoL

### ISSUE THREAD

**Issue by ConqAra** [William758/ZetAspects#38]
when artifact of command is enabled shouldn't aspects either be added to the drop pool automatically or remain unaffected? Otherwise when the elite drop their aspect they are either a red or yellow (whether u have aspects as red or yellow) item and will not involve the aspect.

**Comment by William758** [comment]
Aspects are added to the drop pool if the config aspectWorldUnique is set to false. If an aspect drops while artefact of command is enable and aspectWorldUnique is true then the aspect should be the only option in the command menu from that drop.

**Comment by ConqAra** [comment]
Thank you for clarifying, I misunderstood.
