### ISSUE TITLE
ZetAspects conflicts with BetterUI if any item mods are installed

### ISSUE THREAD

**Issue by HaxTheCharizard** [William758/ZetAspects#39]
Having ZetAspects and BetterUI installed on their own works perfectly fine, but having any additional item mods installed (not including Synergies) causes non-existent items to appear in every players' inventory in multiplayer except for the host.

This item offset prevents any player from seeing what items they actually have unless they open a scrapper.

This could be an issue with the aspect item IDs and how BetterUI tries to scan for them, but doesn't make the right item "hidden" due to an increase in item IDs from additional mods.
(trying to describe this the best I can because of how difficult it was to isolate this)

**Comment by William758** [comment]
The issue is that the inventory networking only supports 256 item ids. Since items are sorted alphabetically and my items start with z, item mods easily push my item ids past 256. https://thunderstore.io/package/RumblingJOSEPH/RemoveItemLimit/ This mod should fix the issue.
