### ISSUE TITLE
Feature request: Config option to completely disable extra effects

### ISSUE THREAD

**Issue by sanity-dance** [William758/ZetAspects#4]
There are extra effects assigned to each aspect- blades on the ice aspect, movement speed on the fire aspect, sap on the lightning aspect, lifedrain on the malachite aspect, etcetera.

If you set the bonus granted by these extra effects to 0, they still show up in the description text in-game. If it is possible, could you add a setting that disables the effects completely if the config option for them is set to -1 or something along those lines?

![image](https://user-images.githubusercontent.com/58183513/104493473-f0935500-5589-11eb-8417-c0bfb46727bb.png)

**Comment by William758** [comment]
I've posted an update allowing most stuff to be disabled and the description not showing disabled stuff.

**Comment by sanity-dance** [comment]
Confirmed working in the newest version.
