### ISSUE TITLE
Silence Between Two Strikes - EliteReworks

### ISSUE THREAD

**Issue by JardonKern** [William758/ZetAspects#42]
If EliteReworks is installed, Aspect of Lightning won't stack bomb damage on subsequent pickups. I know it's because EliteReworks completely overrides ZetAspects stats, but this ends up being the only aspect item which loses stacking potential.
Is it possible to force damage stacking on top of EliteReworks changes?

**Comment by William758** [comment]
Latest update has a config for this that's enabled by default.
