### ISSUE TITLE
Enemies with His Reassurance results in infinite loop

### ISSUE THREAD

**Issue by ILikeEggsToo** [William758/ZetAspects#43]
If the enemies gain the His Reassurance aspect, such as in Simulacrum or Void Fields, the healing cores spawned from dead enemies seem to also inherit the aspect. This causes an infinite loop of healing cores spawning higher and higher up, which never go away.
Perhaps a simple fix would be blacklisting the healing cores from inheriting the His Reassurance item?

**Comment by William758** [comment]
Just posted an update that should prevent the healing cores from inheriting the buff.
