### ISSUE TITLE
Enemy orbs with Silence Between Two Strikes and self-proc indefinitely

### ISSUE THREAD

**Issue by PIEisFANTASTIC** [William758/ZetAspects#44]
Recent patch with the mod has made it so the orbs created by SBTS attacks can recursively proc themselves if stuck to another player or entity. This has instant killed me several times and nearly crashes my game from being attached to drones. (Watched a drone explode for a solid 2 minutes with near 0 FPS while the orbs exploded until it died.)

**Comment by William758** [comment]
This sort of behavior usually happens whenever any mod throws an error, which causes the bomb to never delete itself. I'm going to need a error log to see what caused the issue.

**Comment by PIEisFANTASTIC** [comment]
Let me go back into a run and get a log real quick for ya.

**Comment by PIEisFANTASTIC** [comment]
[LogOutput.log](https://github.com/William758/ZetAspects/files/8587579/LogOutput.log)
Got this to happen pretty quickly in a run, logs for it are definitely in here. If not caused by ZetAspects I apologize for the time wasted, but I appreciate the look either way.

**Comment by PIEisFANTASTIC** [comment]
Oh alrighty, thank you for taking time looking into this and reporting it to the right mod creator lol. I'll go ahead and close this issue.
