### ISSUE TITLE
Bugged aspectDropChance?

### ISSUE THREAD

**Issue by BrandonRosa** [William758/ZetAspects#49]
During my playthroughs, it felt like the default .2% was maybe too high. After changing it to .15% (.15) aspects seem incredibly rare now.

Ive tried some playthroughs with multiple 57 leaf clovers with artifact of honor and swarms enabled. Perhaps its bugged?

**Comment by BrandonRosa** [comment]
Nevermind, it seems i was just getting very very unlucky

**Comment by William758** [comment]
I've done some testing and it seems that some enemies actually never get to the equipment drop chance code for some reason.

I'm currently testing on Sulphur Pools and notice that Alpha Constructs never roll their chance to drop.
