### ISSUE TITLE
Bug report: Setting aspect drop chance has no effect

### ISSUE THREAD

**Issue by sanity-dance** [William758/ZetAspects#5]
Steps to reproduce:

Set dropChance in the config to 100.

Start the game. Kill several elites.

All mods other than ZetAspects and ILLine were disabled.

Log file: 
[AspectChanceLog.txt](https://github.com/William758/ZetAspects/files/5810541/AspectChanceLog.txt)

**Comment by William758** [comment]
Looks like I forgot to load the BuffAPI causing stuff to break. I'll post an update when I finish with all the configs to disable effects.

**Comment by Nordblum** [comment]
Was this fixed in 1.2.0?

**Comment by sanity-dance** [comment]
Yes, this is no longer an issue as of the latest version.
