### ISSUE TITLE
Introduce a config for the drop chance being halved.

### ISSUE THREAD

**Issue by EletricDragonYT** [William758/ZetAspects#50]
The Thunderstore page says that the drop chance is halved every time an aspect is dropped, it would be nice to receive a configuration file that determines the percentage that the drop chance is lowered between 0% and 100%. or even 0% and -100% which increases the drop chance.

**Comment by William758** [comment]
There's already a config which is aspectDropChanceDecay = 0.5, which is where the halving comes from.

There is also aspectDropChanceDecayLimit = 0.25, which limits the drop chance reduction effect to 1/4.
