### ISSUE TITLE
Picking aspects may lead in impossibly high damage

### ISSUE THREAD

**Issue by BrandonRosa** [William758/ZetAspects#51]
I am unsure whether this is from AspectAbilities or ZetAspects, but when I have a run with an aspect this often occurs!
P.S. Great Mod! Its probably my favorite vanilla-style mod!
![Capture](https://user-images.githubusercontent.com/39537164/174246098-1bfaf1e1-6dd5-452c-9e59-1d230060a5e9.PNG)

**Comment by William758** [comment]
Probably not really an issue solely related with aspects. I've seen plenty of people post screenshots of absurd damage numbers that don't have any aspects. Although having aspects probably helps contribute to the issue. Damage tracking is probably bugged and throwing more damaging effects from mods seems to increase the likeliness of it happening.

**Comment by William758** [comment]
I've added a patch to filter out absurdly high damage numbers from the stat sheet.
