### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by Sandersshine** [William758/ZetAspects#54]
Hello author. My friend and I like this mod very much. The only regret for us is that there is no Chinese translation.
So I would like to provide the translation of my native language (Chinese).

What I need to do is to translate the file [merged_lang_tr.txt](https://github.com/William758/ZetAspects/files/7193706/merged_lang_tr.txt) ?

**Comment by William758** [comment]
Hi, Thank you for enjoying the mod and wanting to translate it.

The latest file is : 
[zetaspects_tokens_2724.txt](https://github.com/William758/ZetAspects/files/10744893/zetaspects_tokens_2724.txt)

**Comment by Almph** [comment]
大佬中文翻译咋样了？

**Comment by Sandersshine** [comment]
> 大佬中文翻译咋样了？

临近毕业没时间搞了 托更到明年

**Comment by BTP-G** [comment]
@Sandersshine 如果你没时间的话我可以接手，如何？

**Comment by Sandersshine** [comment]
> @Sandersshine 如果你没时间的话我可以接手，如何？

ok

**Comment by BTP-G** [comment]
ok，好的

**Comment by BTP-G** [comment]
[zetaspects_tokens_2724.txt](https://github.com/William758/ZetAspects/files/12063430/zetaspects_tokens_2724.txt)

**Comment by BTP-G** [comment]
@William758 this is translated file （chinese）
[zetaspects_tokens_2724.txt](https://github.com/William758/ZetAspects/files/12063431/zetaspects_tokens_2724.txt)

**Comment by William758** [comment]
Thank you very much for the translation. I've added the translation to the latest mod update. Let me know if there is anything that needs to be fixed.

**Comment by BTP-G** [comment]
@William758 Update it. 
[zetaspects_tokens_2724.txt](https://github.com/William758/ZetAspects/files/12225134/zetaspects_tokens_2724.txt)

**Comment by MushroomEl** [comment]
@William758 Hello, author, I really like this mod and would like to play it with my friends. I want to further improve the Chinese translation, what should I do? Can I modify and upload this file directly? 
https://github.com/William758/ZetAspects/blob/main/Language.cs
