### ISSUE TITLE
bulwark's absence causes jumping problems

### ISSUE THREAD

**Issue by Hammerkirby123** [William758/ZetAspects#56]
when having the rising tides aspect of darkness "costume" it causes most if not all jumps to stop right when it leaves the ground, effectively cancelling it. getting a different aspect "costume" seems to fix it but some of the aspects don't override darkness' one.
(by costume i mean the look you get when getting the aspect)

**Comment by Hammerkirby123** [comment]
in the order of which costumes overrides which, this is the list with rising tides

void 
unity
alterability
invasion
perfection
corruption
incorporeality
polarity
darkness (troubled one)
earth
fire
lightning
ice

four don't override bulwarks absence

**Comment by Hammerkirby123** [comment]
did not mean to close it

**Comment by William758** [comment]
Seems that the crown has collision enabled which is causing the problem. I've let the mod author of Rising Tides know about the issue at : https://github.com/TheMysticSword/RisingTides/issues/2

**Comment by William758** [comment]
Problem has been fixed.
