### ISSUE TITLE
Glitched aspect log entry among white items if Blighted Elites by Moffein is not installed.

### ISSUE THREAD

**Issue by eGhpGZeMqhlAIRtA1soVFK4JCDnrsxAXjirz97L** [William758/ZetAspects#57]
![Screenshot 2023-07-21 101433](https://github.com/William758/ZetAspects/assets/74626960/43cb5ffd-ba00-4c05-8c3d-cd9d5635bb09)

Installing Blighted Elites replaces this glitched entry with its proper one, in the proper item category.

**Comment by William758** [comment]
Should be fixed now, thanks for letting me know.
