### ISSUE TITLE
NemRisingTides glitched aspect log entries appearing in Logbook despite the mod not being installed.

### ISSUE THREAD

**Issue by eGhpGZeMqhlAIRtA1soVFK4JCDnrsxAXjirz97L** [William758/ZetAspects#58]
![Screenshot 2023-08-06 085052](https://github.com/William758/ZetAspects/assets/74626960/127c9603-0b9f-4d25-a8c2-2827b2aab69f)
![Screenshot 2023-08-06 085107](https://github.com/William758/ZetAspects/assets/74626960/f0620926-e7f5-4666-a141-b1259a538c19)

Hooks are all enabled in the config; disabling the hooks doesn't fix/make things better much.

**Comment by William758** [comment]
They always find a way to show up huh. Thanks again for letting me know, should be fixed now.
