### ISSUE TITLE
MoreElites support

### ISSUE THREAD

**Issue by Phreelosu** [William758/ZetAspects#59]
https://thunderstore.io/package/Nuxlar/MoreElites/

Any chance of the 3 elites being obtainable in the future?
Nuxlar made this one quite stable and doesn't have any issues really

**Comment by William758** [comment]
I remember this being deprecated a while back and I haven't really paid attention to ror2 much so didn't realize he brought it back. I'll see when I can find the time to make an update.

**Comment by Phreelosu** [comment]
well, now that [Sandswept](https://thunderstore.io/package/SandsweptTeam/Sandswept/) is out and has the Motivating elite doing the exact same as Empowering in MoreElites
I'm not sure how you'd approach this conflict

**Comment by Phreelosu** [comment]
oh boy, Starstorm 2's latest update also brings in a new elite called "Empyrean" which practically is all aspects at once lol

maybe I should've opened a new issue for this but since there are two other mods mentioned here missing I thought it has a better place here to be told about unless you are aware.
Also I'm late but happy holidays and thank you for everything you do

**Comment by William758** [comment]
Hey happy holidays. Yeah seems like I have a backlog of mods I need to add support for. Hopefully I'll have the time to add support after new years.

**Comment by Phreelosu** [comment]
https://thunderstore.io/package/TheMysticSword/RisingTides/changelog/ + RisingTides 1.2's Phenakite xD

**Comment by Phreelosu** [comment]
closed as its outdated of a thread
