### ISSUE TITLE
ConvertAspects not working

### ISSUE THREAD

**Issue by True-Oblivion** [William758/ZetAspects#61]
Recently added ZetAspects to a Mod Pack made with my friends but whenever right clicking on the Equipment It will sent out the command in Text Form and not do anything. The Logs show it as the following: "[Info   : Unity Log] <color=#e5eefc><noparse></noparse>: <noparse>ConvertAspect</noparse></color>"

Changing it to red rarity or other settings relating to them being items in the config are not working but I am unsure which mod is the culprit if anyone could help it would be appreciated.

Here is a log from a short solo run using Artifact of Command and Artifact of Honor to test if changing the configs of would do anything.
[LogOutput.log](https://github.com/William758/ZetAspects/files/13695128/LogOutput.log)

**Comment by William758** [comment]
Seems your chat messages don't have usernames.

my log:
[Info   : Unity Log] <color=#e5eefc><noparse>!TPDespair</noparse>: <noparse>ConvertAspect</noparse></color>

your log:
[Info   : Unity Log] <color=#e5eefc><noparse></noparse>: <noparse>ConvertAspect</noparse></color>

You most likely have a mod that makes changes to the chat. I'll try and see if I can get the sender some other way.

**Comment by True-Oblivion** [comment]
After hours of trial and error it seems that TooManyFriends was the culprit. I guess it messes around with the User ID of the command input.

**Comment by William758** [comment]
I believe I've got a solution for the converting. No idea why the red tier config wouldn't work tho.

**Comment by True-Oblivion** [comment]
Updated the mod and retested with TooManyFriends and its working 100% now. U work fast man Thx a lot for the work you put into this mod.
