### ISSUE TITLE
Entropic Fracture does not block incoming damage

### ISSUE THREAD

**Issue by DarSitam** [William758/ZetAspects#65]
void enemies does not block incoming damage either, even when the aspect description says otherwise

**Comment by DarSitam** [comment]
Update : it happens only with LittleGameplayTweaks

**Comment by William758** [comment]
The blocking behavior is implemented in the base game and I just add the text to the description to describe it. LittleGameplayTweaks must be removing this behavior from the void elite type.

**Comment by DarSitam** [comment]
> The blocking behavior is implemented in the base game and I just add the text to the description to describe it. LittleGameplayTweaks must be removing this behavior from the void elite type.

after further tests, it seems that LGT only disabled the bubble with this mod.
i notified the creator of this mod, sorry for the inconvenience
