### ISSUE TITLE
There is no sound when you receive fall damage on the latest version of the mod.

### ISSUE THREAD

**Issue by Nordblum** [William758/ZetAspects#7]
I thought I was going insane, tried disabling all the mods I was suspecting, but I would never suspect this one. After disabling it, the fall damage sound is back. I don't know what this mod has to do with fall damage, but it seems like it has at least something to do with it.

**Comment by William758** [comment]
Alright I've gone ahead and fixed that.  I forgot to check if an attacker existed somewhere.

**Comment by Nordblum** [comment]
Thanks a lot.
