### ISSUE TITLE
SotS update and further support

### ISSUE THREAD

**Issue by Phreelosu** [William758/ZetAspects#73]
hi there, hope you've been well

I know you kinda left the modding scene for a while now, but is there any chance you'd do a compatibility update once the game is stable enough?

**Comment by William758** [comment]
I've been alright I'd say. I wanted to get the mod working when the patch came out, but between being sick and the game being jank I didn't. Just got around to updating the mod. Really hope they fix the game tho.

**Comment by Phreelosu** [comment]
same, happy to see you back though
and thanks for the quick update, hoping for aspect support of SotS elites too 🙏
