### ISSUE TITLE
GoldenCoastPlus change

### ISSUE THREAD

**Issue by Phreelosu** [William758/ZetAspects#75]
hey there, I just revived GoldenCoastPlus under my name as the author abandoned RoR2 modding altogether

the bepin plugin guid is "com.Phreel.GoldenCoastPlusRevived"

everything else should be the same, as I havent changed the content aside from just slight renames

here is the TS package: https://thunderstore.io/package/Phreel/GoldenCoastPlusRevived/

**Comment by William758** [comment]
Just pushed an update. Thank you for maintaining that mod.
