### ISSUE TITLE
Broken health after picking up an aspect

### ISSUE THREAD

**Issue by byKrem** [William758/ZetAspects#78]
After picking up an aspect and moving to next stage the player health broke.
![20240907120952_1](https://github.com/user-attachments/assets/3b3ae922-efab-4a8f-b9f5-a4ed4baec32a)

Other Installed mods:
SOTSFixer (Modpack)
LookingGlass
CommandQueue
MadVeteran_Skinpack
ProperSave
ESCapism

**Comment by byKrem** [comment]
Also incorrect amount of health still remains even after removing aspect from player's inventory by Mithrix
![20240907121835_1](https://github.com/user-attachments/assets/a9a9ceeb-c234-41cd-b941-8fd5b8fa91e9)

**Comment by William758** [comment]
I've downloaded the mods and have been unable to replicate the issue. Can i get a modpack code to make sure i have the exact same mods installed?

**Comment by byKrem** [comment]
Welp. I can't reproduce it now too... Feels strange...
Also by modpack code you mean r2modman profile code? If so here: 0191dee7-bfcc-4615-9b52-895ac4fae7cb

**Comment by byKrem** [comment]
I haven't seen this issue even once since that day, so... I think closing it is a good choice.
