### ISSUE TITLE
Bug report: Silence Between Two Strikes makes you overloading instead of glacial.

### ISSUE THREAD

**Issue by Nordblum** [William758/ZetAspects#8]
Steps to reproduce:
1. Get Silence Between Two Strikes.
2. Expect to become glacial.
3. Become overloading instead.
The buff icon is blue, you get all the overloading effects - shields, electric bombs, damage sapping - everything from the overloading aspect. Didn't test all the other aspects yet, but this didn't seem to happen with the rest of them, otherwise I would've noticed that.

**Comment by William758** [comment]
No, this is correct. Her Biting Embrace is the glacial one. There pretty hard to tell apart because they look so similar.

**Comment by Nordblum** [comment]
Damn, I'm in disbelief. Why didn't I just google the name of the item, what a shame. But still, their icons are really messed up, it's really difficult to tell them apart.
