### ISSUE TITLE
Modded aspect tokens and models broke in 2.9.0

### ISSUE THREAD

**Issue by Phreelosu** [William758/ZetAspects#85]
Augmentum:
![image](https://github.com/user-attachments/assets/33f4dbc6-e096-4f1d-9ad1-708181d41360)

EliteVariety:
![image](https://github.com/user-attachments/assets/21e9e081-fb88-4a97-a76d-0bd6d709cccf)

Sandswept:
![image](https://github.com/user-attachments/assets/0c3a0025-f670-49ff-896f-7d0fe4b0ec40)

MoreElites:
![image](https://github.com/user-attachments/assets/46d2f3b7-9b41-429d-b9e3-120fed0bf2f8)

Aetherium, SpikeStrip and RisingTides seem to work, however **Nemesis Rising Tides aspects doesnt appear at all**

**Comment by William758** [comment]
I've got a variety of mods that I use and everything loaded up fine. I'm not using rising or nem rising so maybe something broke there. I'll need the log to show me exactly what broke during loading.

**Comment by Phreelosu** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17492434/LogOutput.log)
here is log

**Comment by Phreelosu** [comment]
fixed in latest versions
